apiVersion: v1
kind: Pod
metadata:
  name: go-kube
  labels:
    app: go-kube
spec:
  containers:
    - name: go-kube
      image: marimoex/go_kube:latest
      ports:
        - name: http
          containerPort: 8080