apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-kube
  template:
    metadata:
      labels:
        app: go-kube
    spec:
      containers:
        - name: go-kube
          image: marimoex/go_kube:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
