apiVersion: v1
kind: Service
metadata:
 name: app-lb
spec:
 type: LoadBalancer
 ports:
   - name: "http-port"
     protocol: "TCP"
     port: 8080
     targetPort: 8080
     nodePort: 30082
 selector:
   app: go-kube